[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#031F54"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#213C56"

# Color used for almost all text.
textColor = "#fff"